name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Instalar binário do Cypress
        run: npx cypress install

      - name: Rodar testes Cypress
        run: npx cypress run

      - name: Instalar AWS CLI via pip
        run: |
          pip install --upgrade --user awscli
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Fazer upload para S3
        if: always() # mesmo que os testes falhem
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: | 
          TIMESTAMP=$(date +%Y-%m-%d_%H-%M-%S)
          aws s3 cp cypress/screenshots s3://$S3_BUCKET_NAME/cypress/$TIMESTAMP/screenshots/ --recursive
          aws s3 cp cypress/videos s3://$S3_BUCKET_NAME/cypress/$TIMESTAMP/videos/ --recursive